BPlan/urls.py
from django.urls import path
from . import view_common, view_user, views_inventory, view_customer, view_excel

app_name = "BPlan"


urlpatterns = [
    path('test/', view_excel.test, name="test"),

    # path('index/whetherLogin/', view_common.whether_login, name='whether_login'),
    path('index/', view_common.index, name='index'),
    # path('markdown/', view_common.markdown_html, name='markdown'),

    path('login/', view_user.login_html, name='login'),
    # path('login/loginCheck/', view_user.login_check, name='login_check'),
    path('login/logout/', view_user.login_logout, name='login_logout'),
    path('login/record/', view_user.login_record_html, name='login_record_html'),
    # path('login/record/ask/', view_user.login_record_ask_html, name='login_record_ask_html'),
    # path('register/', view_user.register_html, name='register_html'),
    # path('register/check/', view_user.register_check, name='register_check'),
    # path('change/password/', view_user.change_password_html, name='change_password_html'),
    # path('change/password/check/', view_user.change_password_check, name='change_password_check'),
    # path('change/question/', view_user.change_question_html, name='change_question_html'),
    # path('change/question/check/', view_user.change_question_check, name='change_question_check'),
    # path('change/personalInformation/', view_user.change_personal_information, name='change_personal_information'),

    path('inventory/show/all/', views_inventory.inventory_show_all_html, name='inventory_show_all_html'),
    path('inventory/show/detail/', views_inventory.inventory_show_detail_html, name='inventory_show_detail_html'),
    path('inventory/create/', views_inventory.inventory_create, name='inventory_create_html'),
    # path('inventory/create/add/', views_inventory.inventory_create_add, name='inventory_create_add'),
    path('inventory/change/', views_inventory.inventory_change, name='inventory_change_html'),
    # path('inventory/change/add/', views_inventory.inventory_change_add, name='inventory_change_add'),
    path('inventory/change/detail/', views_inventory.inventory_change_detail, name='inventory_change_detail'),
    path('inventory/search/', views_inventory.inventory_search, name='inventory_search'),
    path('inventory/operation/', views_inventory.inventory_operation_html, name='inventory_operation_html'),
    path('inventory/operation/chart/', views_inventory.inventory_operation_chart_html, name='inventory_operation_chart_html'),
    path('inventory/group/create/', views_inventory.inventory_group_create, name='inventory_group_create_html'),
    # path('inventory/group/create/add/', views_inventory.inventory_group_create_add, name='inventory_group_create_add'),

    path('customer/show/all/', view_customer.customer_show_all_html, name='customer_show_all_html'),
    path('customer/show/detail/', view_customer.customer_show_detail_html, name='customer_show_detail_html'),
    path('customer/search/', view_customer.customer_search, name='customer_search'),
    path('customer/create/', view_customer.customer_create_html, name='customer_create_html'),
    # path('customer/create/add/', view_customer.customer_create_add, name='customer_create_add'),
    path('customer/tracking/', view_customer.customer_tracking, name='customer_tracking'),
    path('customer/change/detail/', view_customer.customer_change_detail, name='customer_change_detail'),
    path('customer/excel/', view_customer.customer_excel, name='customer_excel'),

    path('excel/inventory/', view_excel.inventory_excel, name='excel_inventory'),
    path('excel/inventory_operation/', view_excel.inventory_operation_excel, name='excel_inventory_operation'),
    path('excel/customer/', view_excel.customer_excel, name='excel_customer'),  # 导出全部客户信息
    path('excel/login_record', view_excel.login_record_excel, name='excel_login_record'),

    # path('verificationCode/get/', VerificationCode.verification_code, name='getVerificationCode'),

    # WXApi URL:
    # path('wx/login/', WXApi.wx_login_check, name='wx_login_check'),
    # path('wx/logout/', WXApi.wx_logout, name='wx_logout'),
]

ResearchAndTrainingBPlan/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('BPlan/', include('BPlan.urls', namespace="BPlan")),
    path('', RedirectView.as_view(url='BPlan/index/')),  # 如果不输入详细网址，直接重定向到主页
]

BPlan/models.py
from django.db import models


# class Group(models.Model):
#     """组"""
#     group_id = models.CharField(verbose_name='组编号', max_length=12)
#     group_name = models.CharField(verbose_name='组名称', max_length=12)
#     group_create_time = models.DateTimeField(auto_now_add=True, verbose_name='组创建时间')
#
#     def __str__(self):
#         return self.group_name
#
#     class Meta:
#         db_table = "Groups"
#         ordering = ['id']  # 以id为标准升序
#         verbose_name_plural = '分组'


class User(models.Model):
    """用户"""
    '''选项'''
    USER_GENDER_CHOICE = (  # 性别选项
        (True, '男'),
        (False, '女'),
    )
    USER_IDENTITY_CHOICE = (  # 身份选项
        (0, '普通职员'),
        (1, '管理员'),
    )
    # USER_QUESTION_CHOICE = (  # 密保问题选项
    #     (0, '我最喜欢的颜色'),
    #     (1, '我的家乡'),
    #     (2, '我的出生年月（如2000.3.1）'),
    #     (3, '我的小学班主任是'),
    #     (4, '我的初中班主任是'),
    #     (5, '我的高中班主任是'),
    #     (6, '我配偶的姓名'),
    #     (7, '我的大学辅导员是'),
    #     (8, '我父亲的名字'),
    #     (9, '我母亲的名字'),
    #     (10, '我大学里最好的朋友是'),
    #     (11, '我最想去的地方'),
    #     (12, '我的科研训练导师是'),
    # )

    '''基础信息'''
    user_id = models.CharField(verbose_name='用户id', max_length=12)
    user_password = models.CharField(max_length=20, verbose_name='密码')
    # user_group = models.ForeignKey(Group, on_delete=models.CASCADE, verbose_name='所属组')

    '''需要完善的信息'''
    user_name = models.CharField(max_length=12, default='保密', verbose_name='姓名')
    user_gender = models.BooleanField(
        default=True,
        choices=USER_GENDER_CHOICE,
        verbose_name='性别'
    )  # true 代表男性，false 代表女性
    user_identity = models.PositiveSmallIntegerField(
        default=0,
        choices=USER_IDENTITY_CHOICE,
        verbose_name='身份与权限'
    )  # 0:职员，1:管理员
    # user_question = models.PositiveSmallIntegerField(
    #     choices=USER_QUESTION_CHOICE,
    #     default=0,
    #     verbose_name='密保问题'
    # )  # 密保问题
    # user_question_answer = models.CharField(default='', max_length=20, verbose_name='密保问题答案')  # 密保问题答案
    user_create_time = models.DateTimeField(auto_now_add=True, verbose_name='用户注册时间')

    # @classmethod
    # def add_user(cls, user_id, user_password):
    #     """用于增加一个用户"""
    #     user = cls(user_id=user_id, user_password=user_password)
    #     return user

    def __str__(self):
        return self.user_name

    class Meta:
        db_table = "User"
        ordering = ['id']  # 以id为标准升序
        verbose_name_plural = '用户'


class Customer(models.Model):
    """客户信息"""
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='业务填写人')
    # user_id = models.CharField(max_length=12, verbose_name='业务填写人id')
    name = models.CharField(max_length=50, verbose_name='客户名称')
    contact = models.CharField(max_length=20, verbose_name='联系人')
    tel = models.CharField(max_length=20, verbose_name='联系方式')
    project_name = models.CharField(max_length=50, verbose_name='项目名称')
    project_date = models.DateField(verbose_name='项目签订时间')
    project_amount = models.CharField(max_length=20, verbose_name='项目金额')
    payment_method = models.CharField(max_length=20, verbose_name='付款方式')
    mark = models.TextField(max_length=1000, verbose_name='项目技术要求或主要条款', default='无')

    def __str__(self):
        return self.project_name

    class Meta:
        db_table = 'Customer'
        ordering = ['id']
        verbose_name_plural = '客户信息'


class InventoryGroup(models.Model):
    """库存的组"""
    auto_id = models.BigAutoField(primary_key=True, verbose_name='组编号')
    name = models.CharField(max_length=20, verbose_name='组名称')
    # attributes_name = models.CharField(max_length=50, verbose_name='属性的字段名称')  # 以“,”分割
    # attributes_num = models.PositiveSmallIntegerField(verbose_name='属性数量')

    def __str__(self):
        return self.name

    class Meta:
        db_table = "InventoryGroup"
        ordering = ['auto_id']  # 以id为标准升序
        verbose_name_plural = '库存的组'


class Inventory(models.Model):
    """库存"""
    # """选项"""
    # INVENTORY_CATEGORY_CHOICE = (  # 库存类别选项
    #     (0, '电阻'),
    #     (1, '电容'),
    #     (2, '电感'),
    # )

    inventory_id = models.BigAutoField(max_length=12, verbose_name='编号', primary_key=True)
    inventory_name = models.CharField(max_length=20, verbose_name='名称')
    # inventory_category = models.CharField(max_length=12, verbose_name='类别')
    # inventory_category = models.PositiveSmallIntegerField(
    #     default=0,
    #     choices=INVENTORY_CATEGORY_CHOICE,
    #     verbose_name='库存类别'
    # )
    inventory_group = models.ForeignKey(InventoryGroup, on_delete=models.CASCADE, verbose_name='分组')
    inventory_num = models.PositiveIntegerField(verbose_name='数量')
    inventory_unit = models.CharField(max_length=12, default='个', verbose_name='单位')
    inventory_specification = models.CharField(max_length=50, verbose_name='规格')
    # inventory_details = models.TextField(max_length=300, default='无', verbose_name='详细信息')
    # inventory_value = models.IntegerField(default=0, verbose_name='库存的特性值')
    # inventory_package = models.CharField(default='', max_length=20, verbose_name='封装')
    inventory_mark = models.CharField(default='无', max_length=300, verbose_name='备注')
    # inventory_create_user = models.CharField(max_length=12, verbose_name='创建人id')
    # inventory_create_user_name = models.CharField(max_length=20, verbose_name='创建人姓名')
    inventory_create_user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='创建人', related_name='create_user')
    inventory_create_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    # inventory_recent_change_user = models.CharField(max_length=12, verbose_name='最近领用人id')
    # inventory_recent_change_user_name = models.CharField(max_length=20, verbose_name='最近领用人姓名')
    inventory_recent_change_user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='最近领用人', related_name='change_user')
    inventory_recent_change_time = models.DateTimeField(auto_now=True, verbose_name='最近修改时间')

    # @classmethod
    # def add_inventory(
    #         cls,
    #         # inventory_id,
    #         inventory_name,
    #         inventory_group,
    #         inventory_num,
    #         inventory_unit,
    #         # inventory_details,
    #         # inventory_value,
    #         # inventory_package,
    #         inventory_price,
    #         inventory_mark,
    #         inventory_create_user,
    #         inventory_create_user_name,
    # ):
    #     inventory = cls(
    #         # inventory_id=inventory_id,
    #         inventory_name=inventory_name,
    #         inventory_group=inventory_group,
    #         inventory_num=inventory_num,
    #         inventory_unit=inventory_unit,
    #         # inventory_details=inventory_details,
    #         # inventory_value=inventory_value,
    #         # inventory_package=inventory_package,
    #         inventory_price=inventory_price,
    #         inventory_mark=inventory_mark,
    #         inventory_create_user=inventory_create_user,
    #         inventory_create_user_name=inventory_create_user_name,
    #         inventory_recent_change_user=inventory_create_user,
    #         inventory_recent_change_user_name=inventory_create_user_name,
    #     )
    #     return inventory

    def __str__(self):
        return self.inventory_name

    class Meta:
        db_table = "Inventory"
        ordering = ['inventory_id']  # 以id为标准升序
        verbose_name_plural = '库存'


class InventoryOperation(models.Model):
    """对库存的操作，注意在每次新建库存后都要增加一个此对象"""
    '''选项'''
    INVENTORY_OPERATION_CHOICE = (
        (0, '入库'),
        (1, '出库'),
        (2, '创建'),
    )

    '''属性'''
    inventory_operation_create_date = models.DateField(auto_now_add=True, verbose_name='操作日期')
    inventory_operation_create_time = models.DateTimeField(auto_now_add=True, verbose_name='操作时间')
    # inventory_operation_user = models.CharField(max_length=12, verbose_name='操作者id')
    # inventory_operation_user_name = models.CharField(max_length=20, verbose_name='操作者姓名')
    inventory_operation_user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='领用人')
    inventory_operation_user_ip = models.GenericIPAddressField(protocol='both', unpack_ipv4=False, verbose_name='操作者ip')
    inventory_operation_user_browser = models.CharField(max_length=30, default='未知的浏览器', verbose_name='浏览器')
    inventory_operation_user_system = models.CharField(max_length=30, default='未知的系统', verbose_name='操作系统')
    inventory_operation_user_device = models.CharField(max_length=30, default='未知的设备', verbose_name='设备')
    inventory_operation_category = models.PositiveSmallIntegerField(
        default=0,
        choices=INVENTORY_OPERATION_CHOICE,
        verbose_name='操作类别'
    )
    inventory_operation_num = models.PositiveIntegerField(verbose_name='操作数量')
    inventory_operation_object = models.ForeignKey(Inventory, on_delete=models.CASCADE, verbose_name='操作的库存对象')

    inventory_num = models.PositiveIntegerField(verbose_name='库存余量')

    # @classmethod
    # def add_inventory_operation(  # 增加一个库存的操作
    #         cls,
    #         inventory_operation_user,
    #         inventory_operation_user_name,
    #         inventory_operation_user_ip,
    #         inventory_operation_user_browser,
    #         inventory_operation_user_system,
    #         inventory_operation_user_device,
    #         inventory_operation_category,
    #         inventory_operation_num,
    #         inventory_num,
    #         inventory_operation_object,
    # ):
    #     inventory_operation = cls(
    #         inventory_operation_user=inventory_operation_user,
    #         inventory_operation_user_name=inventory_operation_user_name,

templates/PC/user/changePassword.html
{% extends 'PC/base/baseForm.html' %}
{% load staticfiles %}
{% block title %}
修改密码
{% endblock %}
{% block style %}
{#    <style type="text/css">#}
{#        .form{#}
{#            width: 80%;#}
{#        }#}
{#    </style>#}
{% endblock %}
{% block body-title %}
修改密码|忘记密码
{% endblock %}
{% block form %}
{#    <div class="pure-g">#}
{#        <div class="pure-u-1 pure-u-xl-1-2">#}
            <div class="pure-control-group">
                <label for="user_id">您的账号</label>
                <input type="text" name="user_id" id="user_id" value="{{ user_id }}" placeholder="请输入账号" maxlength="12" required/>
            </div>
            <div class="pure-control-group">
                <label for="user_question">您的密保问题</label>
                <select name="user_question" id="user_question">
                    {% for k,v in user_question_choice %}
                        <option value="{{ k }}">{{ v }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="pure-control-group">
                <label for="user_question_answer">您的密保问题答案</label>
                <input type="text" id="user_question_answer" name="user_question_answer" value="" placeholder="请输入密保问题答案" maxlength="20" required/>
            </div>
{#        </div>#}
{#        <div class="pure-u-1 pure-u-xl-1-2">#}
            <div class="pure-control-group">
                <label for="user_password">请输入新的密码</label>
                <input type="password" name="user_password" id="user_password" placeholder="请输入密码" maxlength="20" required/>
            </div>
            <div class="pure-control-group">
                <label for="user_password_again">确认密码</label>
                <input type="password" name="user_password_again" id="user_password_again" placeholder="再次输入密码" maxlength="20" required/>
            </div>

{#            <div class="pure-control-group">#}
{#                <label for="code">验证码</label>#}
{#                <input type="text" name="code" id="code" value="" placeholder="验证码" maxlength="4" minlength="4" required style="width: calc(17em - 100px - 5px)"/>#}
{#                <img class="code" onclick="refreshSrc()"/>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{% endblock %}
{% block button-text %}<i class="iconfont icon-change"></i> 确认修改{% endblock %}
{% block script %}
<script type="text/javascript">
$(document).ready(function () {
    {#$('#change-password').css('color', '#4ab2f6');  /*设置我的标题颜色为蓝色*/#}
    {#refreshSrc();#}
    let error = $('.error');
    let login_button = $('.form-button');
    let user_id = $('#user_id');
    let user_password = $('#user_password');
    let user_password_again = $('#user_password_again');
    {#let code = $('#code');#}
    login_button.click(function () {
        if (user_password.val() !== user_password_again.val()) {
            error.text('两次输入的密码不一致');
            user_password.val("");
            user_password_again.val("");
            return 0;
        }
        login_button.html('<i class="iconfont icon-jiazai"></i> 请稍后...').attr('disabled', 'disabled');  // 改变button中的文字
        if(NoEmpty('<i class="iconfont icon-change"></i> 确认修改', error, login_button)){
            $.ajax({
                url: "{% url 'BPlan:change_password_check' %}",
                type: 'POST',
                data: {
                    'user_id': user_id.val(),
                    'user_password': user_password.val(),
                    {#'code': code.val(),#}
                    'user_question': $('#user_question').val(),
                    'user_question_answer': $('#user_question_answer').val(),
                    "csrfmiddlewaretoken": $("[name='csrfmiddlewaretoken']").val(),
                },
                success: function (result) {
                    {#if (result === 'codeWrong'){#}
                    {#    error.text('验证码错误！');#}
                    {#    code.val("");#}
                    {#    refreshSrc();#}
                    {#    login_button.html('<i class="iconfont icon-change"></i> 确认修改').removeAttr('disabled');#}
                    {#    return 0;#}
                    //}
                    if (result === 'idDoesNotExist') {
                        error.text('您输入的账号不存在');
                        user_id.val("");
                        {#code.val("");#}
                        {#refreshSrc();#}
                        login_button.html('<i class="iconfont icon-change"></i> 确认修改').removeAttr('disabled');
                        return 0;
                    }
                    if (result === 'questionWrong') {
                        error.text('您的密保答案有误');
                        $('#user_question_answer').val("");
                        {#code.val("");#}
                        {#refreshSrc();#}
                        login_button.html('<i class="iconfont icon-change"></i> 确认修改').removeAttr('disabled');
                        return 0;
                    }
                    if (result === 'success') {
                        error.text("");
                        $("form").hide(1000);
                        $(".body-title").text("修改密码成功请重新登录");
                        $.ajax({
                            url: '{% url 'BPlan:whether_login' %}',
                            success: function(result){
                                if (result['login_status'] === 0) {
                                    $('.header-button').css('display', 'block');
                                    $('.header-user').css('display', 'none');
                                } else{
                                    $('.header-user').css('display', 'block');
                                    $('.header-button').css('display', 'none');
                                    $('.header-user-name').text(result['user_name']);
                                }
                            }
                        });
                        return 1;
                    }
                },
            })
        }
    })
})
</script>
{% endblock %}

templates/PC/user/changePersonalInformationChange.html
{% extends 'PC/base/baseForm.html' %}
{% load staticfiles %}
{% block title %}修改个人信息{% endblock %}
{% block body-title %}
修改个人信息
{% endblock %}
{% block style %}
<style>
.pure-form-aligned .pure-control-group label{
    width: auto;
}
</style>
{% endblock %}
{% block form %}
    <div class="pure-control-group">
        <label for="user_name">姓名</label>
        <input type="text" name="user_name" id="user_name" value="{{ user.user_name }}" placeholder="请输入姓名" maxlength="12" required/>
    </div>
    <div class="pure-control-group">
        <label for="user_gender">性别</label>
        <select name="user_gender" id="user_gender">
            {% for k,v in user.USER_GENDER_CHOICE %}
                <option value="{{ k }}" {% if user.user_gender == k %} selected {% endif %}>{{ v }}</option>
            {% endfor %}
        </select>
    </div>
{#    <div class="pure-control-group">#}
{#        <label for="user_identity">用户身份</label>#}
{#        <select name="user_identity" id="user_identity">#}
{#            {% for k,v in user.USER_IDENTITY_CHOICE %}#}
{#                <option value="{{ k }}" {% if user.user_identity == k %} selected {% endif %}>{{ v }}</option>#}
{#            {% endfor %}#}
{#        </select>#}
{#    </div>#}
{#    <div class="pure-control-group">#}
{#        <label for="code">验证码</label>#}
{#        <input type="text" name="code" id="code" value="" placeholder="验证码" maxlength="4" minlength="4" required style="width: calc(17em - 100px - 5px)"/>#}
{#        <img class="code" onclick="refreshSrc()"/>#}
{#    </div>#}
{% endblock %}
{% block button-text %}
<i class="iconfont icon-change"></i> 确认修改(不建议修改姓名)
{% endblock %}
{% block script %}
<script>
$(document).ready(function () {
    {#refreshSrc();#}
    let error = $('.error');
    let change_button = $('.form-button');
    {#let code = $('#code');#}
    change_button.click(function () {
        change_button.html('<i class="iconfont icon-jiazai"></i> 请稍后...').attr('disabled', 'disabled');  // 改变button中的文字
        if (NoEmpty('<i class="iconfont icon-change"></i> 确认修改(不建议修改姓名)', error, change_button)) {
            $.ajax({
                url: "{% url 'BPlan:change_personal_information' %}",
                type: "POST",
                data: {
                    'user_name': $('#user_name').val(),
                    'user_gender': $('#user_gender').val(),
                    {#'user_identity': $('#user_identity').val(),#}
                    {#'code': code.val(),#}
                    "csrfmiddlewaretoken":$("[name='csrfmiddlewaretoken']").val(),
                },
                success: function (result) {
                    if (result === 'success') {
                        error.text("");
                        $("form").hide(1000);
                        $(".body-title").text("修改成功");
                        return 1;
                    }
                }
            })
        }
    })
})
</script>
{% endblock %}

templates/PC/user/changePersonalInformationShow.html
{% extends 'PC/base/baseDetail.html' %}
{% load staticfiles %}
{% block title %}个人信息{% endblock %}
{% block body-title %}
个人信息
{% endblock %}
{% block detail-contain %}
    <h1>我的ID</h1>
    <li>{{ user.user_id}}</li>
    <h1>姓名</h1>
    <li>{{ user.user_name }}</li>
    <h1>性别</h1>
    <li>{{ user.get_user_gender_display }}</li>
    <h1>身份</h1>
    <li>{{ user.get_user_identity_display }}</li>
    <h1>注册时间</h1>
    <li>{{ user.user_create_time }}</li>
    <h1>库存操作</h1>
    <li>创建 {{ inventory_create_num }}</li>
    <li>入库 {{ inventory_in_num }}</li>
    <li>出库 {{ inventory_out_num }}</li>
{% endblock %}
{% block detail-footer %}
<div class="pure-u-1">
<button id="change"><i class="iconfont icon-change"></i> 修改我的信息</button>
</div>
{% endblock %}
{% block script %}
<script>
$(document).ready(function () {
    $('#change').click(function () {
        window.location.href = '{% url "BPlan:change_personal_information" %}?page=change'
    })
})
</script>
{% endblock %}

templates/PC/user/loginRecordShow.html
{% extends 'PC/base/baseShow.html' %}
{% block title %}
我的访问记录
{% endblock %}
{% block style %}
<style>
.show-body-card-footer{
    text-align: center;
}
.show-body-card{
    height: 230px;
}
</style>
{% endblock %}
{% block body-title %}
我的访问记录
{% endblock %}
{% block show-body %}
    {% if page.object_list.count != 0 %}
        <div class="table-box">
            <table class="show-table">
                <thead>
                <tr>
                    <th>用户</th>
                    <th>登录时间</th>
                    <th>IP</th>
                    <th>浏览器</th>
                    <th>操作系统</th>
                    <th>设备</th>
                </tr>
                </thead>
                <tbody>
                {% for log in page.object_list %}
                    <tr>
                        <td>{{ log.login_user }}</td>
                        <td>{{ log.login_time }}</td>
                        <td>{{ log.login_ip }}</td>
                        <td>{{ log.login_browser }}</td>
                        <td>{{ log.login_system }}</td>
                        <td>{{ log.login_device }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    {% endif %}
{#    {% if paginator == '' %}#}
{#        <p style="text-align: center;font-size: 2em;background-color: #1f8dd6;color: white;">>>抱歉，未找到您的登录记录<<</p>#}
{#    {% else %}#}
{#        <div class="pure-g">#}
{#        {% for log in paginator %}#}
{#            <div class="pure-u-1 pure-u-md-1-3">#}
{#            <div class="show-body-card">#}
{#                <div class="show-body-card-header">#}
{#                    <div class="inventory-name"><label>用户名</label> {{ log.login_user.user_name }}</div>#}
{#                    <div class="inventory-id"><label>ID</label> {{ log.login_user.user_id }}</div>#}
{#                </div>#}
{#                <div class="show-body-card-body">#}
{#                    登录IP：{{ log.login_ip }}<br>#}
{#                    浏览器：{{ log.login_browser }}<br>#}
{#                    操作系统：{{ log.login_system }}<br>#}
{#                    设备：{{ log.login_device }}<br>#}
{#                    登录位置：{{ log.login_location }}<br>#}
{#                </div>#}
{#                <div class="show-body-card-footer">{{ log.login_time }}</div>#}
{#            </div>#}
{#            </div>#}
{#        {% endfor %}#}
{#        </div>#}
{#    {% endif %}#}
{% endblock %}
{% block script %}
    <script>
        $(document).ready(function () {
            $('#excel').click(function () {
                window.location.href = '{% url "BPlan:excel_login_record" %}';
            });
        })
    </script>
{% endblock %}

templates/PC/user/loginold.html
{% extends 'PC/base/baseForm.html' %}
{% load staticfiles %}
{% block title %}登录{% endblock %}
{% block style %}
    <style type="text/css">
    #forget{
        display: block;
        color: white;
        text-decoration: none;
        text-align: center;
        margin-top: 1em;
    }
    .pure-form-aligned .pure-control-group label{
        width: auto;
    }
    </style>
{% endblock %}
{% block body-title %}用户登录{% endblock %}
{% block form %}
    <div class="pure-control-group">
        <label for="user_id">账号</label>
        <input type="text" name="user_id" id="user_id" value="" placeholder="请输入账号" maxlength="12" required/>
    </div>
    <div class="pure-control-group">
        <label for="user_password">密码</label>
        <input type="password" name="user_password" id="user_password" placeholder="请输入密码" maxlength="20" required/>
    </div>
    <div class="pure-control-group">
{#        <label for="code">验证码</label>#}
{#        <input type="text" name="code" id="code" value="" placeholder="验证码" maxlength="4" minlength="4" required style="width: calc(17em - 100px - 5px); display: inline-block"/>#}
{#        <img class="code" onclick="refreshSrc()"/>#}
        <a href="{% url 'BPlan:change_password_html' %}" id="forget">忘记密码？</a>
    </div>
{% endblock %}
{% block button-text %}
<i class="iconfont icon-wancheng"></i> 登录
{% endblock %}
{% block script %}
    <script type="text/javascript">
    $(document).ready(function () {
        let login_button = $('.form-button');
        {#refreshSrc();#}
        let user_id = $('#user_id');
        let user_password = $('#user_password');
        {#let code = $('#code');#}
        let error = $('.error');
        login_button.click(function () {
            if(NoEmpty('<i class="iconfont icon-wancheng"></i> 登录', error, login_button)){
                $.ajax({
                    url: '{% url 'BPlan:login_check' %}',
                    data: {
                        'user_id': user_id.val(),
                        'user_password': user_password.val(),
                        {#'code': code.val(),#}
                        "csrfmiddlewaretoken":$("[name='csrfmiddlewaretoken']").val(),
                    },
                    type: 'POST',
                    success: function (result) {
                        {#if (result === 'codeWrong'){#}
                        {#    error.text('验证码错误！');#}
                        {#    code.val("");#}
                        {#    refreshSrc();#}
                        {#    return 0;#}
                        //}
                        if (result === 'idDoesNotExist') {
                            error.text('您输入的用户名不存在');
                            user_id.val("");
                            {#code.val("");#}
                            {#refreshSrc();#}
                            return 0;
                        }
                        if (result === 'passwordWrong') {
                            error.text('用户名或密码错误');
                            user_password.val("");
                            {#code.val("");#}
                            {#refreshSrc();#}
                            return 0;
                        }
                        if (result === 'successLogin') {
                            window.location.href="{% url 'BPlan:index' %}";
                            return 1;
                        }
                    },
                })
            }
        })
    })
    </script>
{% endblock %}