BPlan/urls.py
from django.urls import path
from . import view_common, view_user, views_inventory, view_customer, view_excel

app_name = "BPlan"


urlpatterns = [
    path('test/', view_excel.test, name="test"),

    # path('index/whetherLogin/', view_common.whether_login, name='whether_login'),
    path('index/', view_common.index, name='index'),
    # path('markdown/', view_common.markdown_html, name='markdown'),

    path('login/', view_user.login_html, name='login'),
    # path('login/loginCheck/', view_user.login_check, name='login_check'),
    path('login/logout/', view_user.login_logout, name='login_logout'),
    path('login/record/', view_user.login_record_html, name='login_record_html'),
    # path('login/record/ask/', view_user.login_record_ask_html, name='login_record_ask_html'),
    # path('register/', view_user.register_html, name='register_html'),
    # path('register/check/', view_user.register_check, name='register_check'),
    # path('change/password/', view_user.change_password_html, name='change_password_html'),
    # path('change/password/check/', view_user.change_password_check, name='change_password_check'),
    # path('change/question/', view_user.change_question_html, name='change_question_html'),
    # path('change/question/check/', view_user.change_question_check, name='change_question_check'),
    # path('change/personalInformation/', view_user.change_personal_information, name='change_personal_information'),

    path('inventory/show/all/', views_inventory.inventory_show_all_html, name='inventory_show_all_html'),
    path('inventory/show/detail/', views_inventory.inventory_show_detail_html, name='inventory_show_detail_html'),
    path('inventory/create/', views_inventory.inventory_create, name='inventory_create_html'),
    # path('inventory/create/add/', views_inventory.inventory_create_add, name='inventory_create_add'),
    path('inventory/change/', views_inventory.inventory_change, name='inventory_change_html'),
    # path('inventory/change/add/', views_inventory.inventory_change_add, name='inventory_change_add'),
    path('inventory/change/detail/', views_inventory.inventory_change_detail, name='inventory_change_detail'),
    path('inventory/search/', views_inventory.inventory_search, name='inventory_search'),
    path('inventory/operation/', views_inventory.inventory_operation_html, name='inventory_operation_html'),
    path('inventory/operation/chart/', views_inventory.inventory_operation_chart_html, name='inventory_operation_chart_html'),
    path('inventory/group/create/', views_inventory.inventory_group_create, name='inventory_group_create_html'),
    # path('inventory/group/create/add/', views_inventory.inventory_group_create_add, name='inventory_group_create_add'),

    path('customer/show/all/', view_customer.customer_show_all_html, name='customer_show_all_html'),
    path('customer/show/detail/', view_customer.customer_show_detail_html, name='customer_show_detail_html'),
    path('customer/search/', view_customer.customer_search, name='customer_search'),
    path('customer/create/', view_customer.customer_create_html, name='customer_create_html'),
    # path('customer/create/add/', view_customer.customer_create_add, name='customer_create_add'),
    path('customer/tracking/', view_customer.customer_tracking, name='customer_tracking'),
    path('customer/change/detail/', view_customer.customer_change_detail, name='customer_change_detail'),
    path('customer/excel/', view_customer.customer_excel, name='customer_excel'),

    path('excel/inventory/', view_excel.inventory_excel, name='excel_inventory'),
    path('excel/inventory_operation/', view_excel.inventory_operation_excel, name='excel_inventory_operation'),
    path('excel/customer/', view_excel.customer_excel, name='excel_customer'),  # 导出全部客户信息
    path('excel/login_record', view_excel.login_record_excel, name='excel_login_record'),

    # path('verificationCode/get/', VerificationCode.verification_code, name='getVerificationCode'),

    # WXApi URL:
    # path('wx/login/', WXApi.wx_login_check, name='wx_login_check'),
    # path('wx/logout/', WXApi.wx_logout, name='wx_logout'),
]

ResearchAndTrainingBPlan/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('BPlan/', include('BPlan.urls', namespace="BPlan")),
    path('', RedirectView.as_view(url='BPlan/index/')),  # 如果不输入详细网址，直接重定向到主页
]

BPlan/models.py
from django.db import models


# class Group(models.Model):
#     """组"""
#     group_id = models.CharField(verbose_name='组编号', max_length=12)
#     group_name = models.CharField(verbose_name='组名称', max_length=12)
#     group_create_time = models.DateTimeField(auto_now_add=True, verbose_name='组创建时间')
#
#     def __str__(self):
#         return self.group_name
#
#     class Meta:
#         db_table = "Groups"
#         ordering = ['id']  # 以id为标准升序
#         verbose_name_plural = '分组'


class User(models.Model):
    """用户"""
    '''选项'''
    USER_GENDER_CHOICE = (  # 性别选项
        (True, '男'),
        (False, '女'),
    )
    USER_IDENTITY_CHOICE = (  # 身份选项
        (0, '普通职员'),
        (1, '管理员'),
    )
    # USER_QUESTION_CHOICE = (  # 密保问题选项
    #     (0, '我最喜欢的颜色'),
    #     (1, '我的家乡'),
    #     (2, '我的出生年月（如2000.3.1）'),
    #     (3, '我的小学班主任是'),
    #     (4, '我的初中班主任是'),
    #     (5, '我的高中班主任是'),
    #     (6, '我配偶的姓名'),
    #     (7, '我的大学辅导员是'),
    #     (8, '我父亲的名字'),
    #     (9, '我母亲的名字'),
    #     (10, '我大学里最好的朋友是'),
    #     (11, '我最想去的地方'),
    #     (12, '我的科研训练导师是'),
    # )

    '''基础信息'''
    user_id = models.CharField(verbose_name='用户id', max_length=12)
    user_password = models.CharField(max_length=20, verbose_name='密码')
    # user_group = models.ForeignKey(Group, on_delete=models.CASCADE, verbose_name='所属组')

    '''需要完善的信息'''
    user_name = models.CharField(max_length=12, default='保密', verbose_name='姓名')
    user_gender = models.BooleanField(
        default=True,
        choices=USER_GENDER_CHOICE,
        verbose_name='性别'
    )  # true 代表男性，false 代表女性
    user_identity = models.PositiveSmallIntegerField(
        default=0,
        choices=USER_IDENTITY_CHOICE,
        verbose_name='身份与权限'
    )  # 0:职员，1:管理员
    # user_question = models.PositiveSmallIntegerField(
    #     choices=USER_QUESTION_CHOICE,
    #     default=0,
    #     verbose_name='密保问题'
    # )  # 密保问题
    # user_question_answer = models.CharField(default='', max_length=20, verbose_name='密保问题答案')  # 密保问题答案
    user_create_time = models.DateTimeField(auto_now_add=True, verbose_name='用户注册时间')

    # @classmethod
    # def add_user(cls, user_id, user_password):
    #     """用于增加一个用户"""
    #     user = cls(user_id=user_id, user_password=user_password)
    #     return user

    def __str__(self):
        return self.user_name

    class Meta:
        db_table = "User"
        ordering = ['id']  # 以id为标准升序
        verbose_name_plural = '用户'


class Customer(models.Model):
    """客户信息"""
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='业务填写人')
    # user_id = models.CharField(max_length=12, verbose_name='业务填写人id')
    name = models.CharField(max_length=50, verbose_name='客户名称')
    contact = models.CharField(max_length=20, verbose_name='联系人')
    tel = models.CharField(max_length=20, verbose_name='联系方式')
    project_name = models.CharField(max_length=50, verbose_name='项目名称')
    project_date = models.DateField(verbose_name='项目签订时间')
    project_amount = models.CharField(max_length=20, verbose_name='项目金额')
    payment_method = models.CharField(max_length=20, verbose_name='付款方式')
    mark = models.TextField(max_length=1000, verbose_name='项目技术要求或主要条款', default='无')

    def __str__(self):
        return self.project_name

    class Meta:
        db_table = 'Customer'
        ordering = ['id']
        verbose_name_plural = '客户信息'


class InventoryGroup(models.Model):
    """库存的组"""
    auto_id = models.BigAutoField(primary_key=True, verbose_name='组编号')
    name = models.CharField(max_length=20, verbose_name='组名称')
    # attributes_name = models.CharField(max_length=50, verbose_name='属性的字段名称')  # 以“,”分割
    # attributes_num = models.PositiveSmallIntegerField(verbose_name='属性数量')

    def __str__(self):
        return self.name

    class Meta:
        db_table = "InventoryGroup"
        ordering = ['auto_id']  # 以id为标准升序
        verbose_name_plural = '库存的组'


class Inventory(models.Model):
    """库存"""
    # """选项"""
    # INVENTORY_CATEGORY_CHOICE = (  # 库存类别选项
    #     (0, '电阻'),
    #     (1, '电容'),
    #     (2, '电感'),
    # )

    inventory_id = models.BigAutoField(max_length=12, verbose_name='编号', primary_key=True)
    inventory_name = models.CharField(max_length=20, verbose_name='名称')
    # inventory_category = models.CharField(max_length=12, verbose_name='类别')
    # inventory_category = models.PositiveSmallIntegerField(
    #     default=0,
    #     choices=INVENTORY_CATEGORY_CHOICE,
    #     verbose_name='库存类别'
    # )
    inventory_group = models.ForeignKey(InventoryGroup, on_delete=models.CASCADE, verbose_name='分组')
    inventory_num = models.PositiveIntegerField(verbose_name='数量')
    inventory_unit = models.CharField(max_length=12, default='个', verbose_name='单位')
    inventory_specification = models.CharField(max_length=50, verbose_name='规格')
    # inventory_details = models.TextField(max_length=300, default='无', verbose_name='详细信息')
    # inventory_value = models.IntegerField(default=0, verbose_name='库存的特性值')
    # inventory_package = models.CharField(default='', max_length=20, verbose_name='封装')
    inventory_mark = models.CharField(default='无', max_length=300, verbose_name='备注')
    # inventory_create_user = models.CharField(max_length=12, verbose_name='创建人id')
    # inventory_create_user_name = models.CharField(max_length=20, verbose_name='创建人姓名')
    inventory_create_user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='创建人', related_name='create_user')
    inventory_create_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    # inventory_recent_change_user = models.CharField(max_length=12, verbose_name='最近领用人id')
    # inventory_recent_change_user_name = models.CharField(max_length=20, verbose_name='最近领用人姓名')
    inventory_recent_change_user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='最近领用人', related_name='change_user')
    inventory_recent_change_time = models.DateTimeField(auto_now=True, verbose_name='最近修改时间')

    # @classmethod
    # def add_inventory(
    #         cls,
    #         # inventory_id,
    #         inventory_name,
    #         inventory_group,
    #         inventory_num,
    #         inventory_unit,
    #         # inventory_details,
    #         # inventory_value,
    #         # inventory_package,
    #         inventory_price,
    #         inventory_mark,
    #         inventory_create_user,
    #         inventory_create_user_name,
    # ):
    #     inventory = cls(
    #         # inventory_id=inventory_id,
    #         inventory_name=inventory_name,
    #         inventory_group=inventory_group,
    #         inventory_num=inventory_num,
    #         inventory_unit=inventory_unit,
    #         # inventory_details=inventory_details,
    #         # inventory_value=inventory_value,
    #         # inventory_package=inventory_package,
    #         inventory_price=inventory_price,
    #         inventory_mark=inventory_mark,
    #         inventory_create_user=inventory_create_user,
    #         inventory_create_user_name=inventory_create_user_name,
    #         inventory_recent_change_user=inventory_create_user,
    #         inventory_recent_change_user_name=inventory_create_user_name,
    #     )
    #     return inventory

    def __str__(self):
        return self.inventory_name

    class Meta:
        db_table = "Inventory"
        ordering = ['inventory_id']  # 以id为标准升序
        verbose_name_plural = '库存'


class InventoryOperation(models.Model):
    """对库存的操作，注意在每次新建库存后都要增加一个此对象"""
    '''选项'''
    INVENTORY_OPERATION_CHOICE = (
        (0, '入库'),
        (1, '出库'),
        (2, '创建'),
    )

    '''属性'''
    inventory_operation_create_date = models.DateField(auto_now_add=True, verbose_name='操作日期')
    inventory_operation_create_time = models.DateTimeField(auto_now_add=True, verbose_name='操作时间')
    # inventory_operation_user = models.CharField(max_length=12, verbose_name='操作者id')
    # inventory_operation_user_name = models.CharField(max_length=20, verbose_name='操作者姓名')
    inventory_operation_user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='领用人')
    inventory_operation_user_ip = models.GenericIPAddressField(protocol='both', unpack_ipv4=False, verbose_name='操作者ip')
    inventory_operation_user_browser = models.CharField(max_length=30, default='未知的浏览器', verbose_name='浏览器')
    inventory_operation_user_system = models.CharField(max_length=30, default='未知的系统', verbose_name='操作系统')
    inventory_operation_user_device = models.CharField(max_length=30, default='未知的设备', verbose_name='设备')
    inventory_operation_category = models.PositiveSmallIntegerField(
        default=0,
        choices=INVENTORY_OPERATION_CHOICE,
        verbose_name='操作类别'
    )
    inventory_operation_num = models.PositiveIntegerField(verbose_name='操作数量')
    inventory_operation_object = models.ForeignKey(Inventory, on_delete=models.CASCADE, verbose_name='操作的库存对象')

    inventory_num = models.PositiveIntegerField(verbose_name='库存余量')

    # @classmethod
    # def add_inventory_operation(  # 增加一个库存的操作
    #         cls,
    #         inventory_operation_user,
    #         inventory_operation_user_name,
    #         inventory_operation_user_ip,
    #         inventory_operation_user_browser,
    #         inventory_operation_user_system,
    #         inventory_operation_user_device,
    #         inventory_operation_category,
    #         inventory_operation_num,
    #         inventory_num,
    #         inventory_operation_object,
    # ):
    #     inventory_operation = cls(
    #         inventory_operation_user=inventory_operation_user,
    #         inventory_operation_user_name=inventory_operation_user_name,

templates/PC/inventory/inventoryOperationSearch.html
{% extends 'PC/base/baseForm.html' %}
{% block title %}
查询库存操作记录
{% endblock %}
{% block body-title %}
查询库存操作记录
{% endblock %}
{% block style %}

{% endblock %}
{% block form %}
    <div class="pure-control-group">
        <label for="id">库存ID</label>
        <input type="search" name="id" id="id" value="" placeholder="请输入库存的ID" maxlength="12" required />
    </div>
{% endblock %}
{% block button-text %}
<i class="iconfont icon-search"></i> 查询
{% endblock %}
{% block script %}
<script>
$(document).ready(function () {
    $('button').click(function () {
        if (NoEmpty('<i class="iconfont icon-search"></i> 查询', $('#error'), $('.form-button'))) {
            window.location.href = "{% url 'BPlan:inventory_operation_html' %}?type=inventory&id="+$('#id').val()
        }
    })
})
</script>
{% endblock %}

templates/PC/inventory/inventorySearch.html
{% extends 'PC/base/baseShow.html' %}
{% block title %}
    查找库存
{% endblock %}
{% block style %}
    <style>
        .body-title {
            font-size: 1em;
            text-align: center;
            width: 85%;
            margin: 70px auto;
            color: black;
            border-bottom: white solid 2px;
        }

        .pure-form select {
            padding: 0 .6em;
            height: 38.8px;
        }

        .show-footer {
            display: none;
        }

        .search-button {
            color: white;
        {#display: block;#} height: 2.3em;
            width: 6em;
            margin: 0;
            padding: 0;
            background-color: var(--bkcolor);
            border: solid white 2px;
            border-radius: 3px;
            transition: background-color 0.5s;
            -webkit-transition: background-color 0.5s;
        }

        .search-button:hover {
            color: var(--bkcolor);
            background-color: white;
        }

        @media only screen and (max-width: 768px) {
            .body-title {
                font-size: 1em;
                padding: 20px 0;
                letter-spacing: normal;
                margin: 20px auto;
                width: 100%;
            }

            .search-button {
                display: none;
            }
        }
    </style>
{% endblock %}
{% block body-title %}
    <form class="pure-form" method="get" action="{% url 'BPlan:inventory_search' %}">
        <select id="search_type" name="search_type" style="display: inline-block">
            <option value="all">综合查询</option>
            {#        <option value="inventory_id">ID</option>#}
            <option value="inventory_name">名称</option>
            <option value="inventory_num">库存数量</option>
            <option value="inventory_specification">规格</option>
            <option value="inventory_mark">备注</option>
            <option value="inventory_create_user_name">创建人</option>
            <option value="inventory_recent_change_user_name">修改人</option>
        </select>
        <input type="search" class="" name="search" id="search" placeholder="请输入关键词查询" required maxlength="20"
               style="display: inline-block; margin: 0" value="{{ search }}">
        <button type="submit" class="search-button">查询库存</button>
    </form>
{% endblock %}
{% block show-body %}
    {% if search_type == '' %}
    {% elif paginator.count == 0 %}
        <p class="not-found">>>抱歉，未找到相关库存信息<<</p>
    {% else %}
        <div class="table-box">
            <table class="show-table">
                <thead>
                <tr>
                    <th>库存ID</th>
                    <th>库存分组</th>
                    <th>库存名称</th>
                    <th>库存数量</th>
                    <th>单位</th>
                    <th>规格</th>
                    <th>备注</th>
                    <th>最近领用人</th>
                    <th>最近领用日期</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for inventory in page.object_list %}
                    <tr>
                        <td>{{ inventory.inventory_id }}</td>
                        <td>{{ inventory.inventory_group }}</td>
                        <td>{{ inventory.inventory_name }}</td>
                        <td>{{ inventory.inventory_num }}</td>
                        <td>{{ inventory.inventory_unit }}</td>
                        <td>{{ inventory.inventory_specification }}</td>
                        <td>{{ inventory.inventory_mark }}</td>
                        <td>{{ inventory.inventory_recent_change_user }}</td>
                        <td>{{ inventory.inventory_recent_change_time | date:"Y-m-d" }}</td>
                        <td>
                            {% if request.session.user_identity %}
                            <a href="{% url 'BPlan:inventory_change_html' %}?type=0&id={{ inventory.inventory_id }}">入库</a>
                            <a href="{% url 'BPlan:inventory_change_html' %}?type=1&id={{ inventory.inventory_id }}">出库</a>
                            {% endif %}
                            <a href="{% url 'BPlan:inventory_show_detail_html' %}?id={{ inventory.inventory_id }}">详细信息</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        {#    <div class="pure-g">#}
        {#    {% for inventory in paginator %}#}
        {#        <div class="pure-u-1 pure-u-md-1-3">#}
        {#            <div class="show-body-card">#}
        {#                <div class="show-body-card-header">#}
        {#                    <div class="inventory-name"><label>名称</label> {{ inventory.inventory_name }}</div>#}
        {#                    <div class="inventory-id">{# <i class="iconfont icon-user-id"></i> {{ inventory.inventory_id }}&nbsp;&nbsp; #}
{#        <label>创建者</label> {{ inventory.inventory_create_user_name }}&nbsp;&nbsp;<label>创建日期</label>#}
{#        {{ inventory.inventory_create_time.month }}月{{ inventory.inventory_create_time.day }}日</div>#}
        {#                </div>#}
        {#                <div class="show-body-card-body">#}
        {#                    库存分组：{{ inventory.inventory_group }}<br>#}
        {#                    库存数量：{{ inventory.inventory_num }}<br>#}
        {#                    单价：{{ inventory.inventory_price }}<br>#}
        {#                    备注：{{ inventory.inventory_mark }}<br>#}
        {#                </div>#}
        {#                <div class="show-body-card-footer">#}
        {#                    <a class="show-body-card-footer-a" href="{% url 'BPlan:inventory_change_html' %}?type=0&id={{ inventory.inventory_id }}">入库</a>#}
        {#                    <a class="show-body-card-footer-a" href="{% url 'BPlan:inventory_change_html' %}?type=1&id={{ inventory.inventory_id }}">出库</a>#}
        {#                    <a class="show-body-card-footer-a" href="{% url 'BPlan:inventory_show_detail_html' %}?id={{ inventory.inventory_id }}">详细信息</a>#}
        {#                </div>#}
        {#            </div>#}
        {#        </div>#}
        {#    {% endfor %}#}
        {#    </div>#}
    {% endif %}
{% endblock %}
{% block script %}
    <script>
        $(document).ready(function () {
            $('option').each(function () {
                if ($(this).val() === '{{ search_type }}') {
                    $(this).attr('selected', 'selected');
                } else {
                    $(this).removeAttr('selected');
                }
            });
            $('#excel').click(function () {
                window.location.href = '{% url "BPlan:excel_inventory" %}';
            });
        })
    </script>
{% endblock %}

templates/PC/inventory/inventoryShowAll.html
{% extends 'PC/base/baseShow.html' %}
{% load staticfiles %}
{% block title %}
    全部库存
{% endblock %}
{% block body-title %}
    全部库存
{% endblock %}
{% block group-choice %}
    <div class="pure-g body-title" id="groups">
        <div class="pure-u-1 pure-u-md-1-3">
            <a class="group-choice" href="{% url 'BPlan:inventory_show_all_html' %}">全部</a>
        </div>
        {% for group in group_list %}
            <div class="pure-u-1 pure-u-md-1-3">
                <a class="group-choice"
                   href="?group={{ group.auto_id }}">{{ group.name }}</a>
            </div>
        {% endfor %}
    </div>
{% endblock %}
{% block show-body %}
    <div class="groups-switch">
        <div class="groups-switch-1"></div>
        <div class="groups-switch-2"></div>
    </div>
    {% if paginator.count > 0 %}
        <div class="table-box">
            <table class="show-table">
                <thead>
                <tr>
                    <th>库存ID</th>
                    <th>库存分组</th>
                    <th>库存名称</th>
                    <th>库存数量</th>
                    <th>单位</th>
                    <th>规格</th>
                    <th>备注</th>
                    <th>最近领用人</th>
                    <th>最近领用日期</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for inventory in page.object_list %}
                    <tr>
                        <td>{{ inventory.inventory_id }}</td>
                        <td>{{ inventory.inventory_group }}</td>
                        <td>{{ inventory.inventory_name }}</td>
                        <td>{{ inventory.inventory_num }}</td>
                        <td>{{ inventory.inventory_unit }}</td>
                        <td>{{ inventory.inventory_specification }}</td>
                        <td>{{ inventory.inventory_mark }}</td>
                        <td>{{ inventory.inventory_recent_change_user }}</td>
                        <td>{{ inventory.inventory_recent_change_time | date:"Y-m-d" }}</td>
                        <td>
                            {% if request.session.user_identity %}
                            <a href="{% url 'BPlan:inventory_change_html' %}?type=0&id={{ inventory.inventory_id }}">入库</a>
                            <a href="{% url 'BPlan:inventory_change_html' %}?type=1&id={{ inventory.inventory_id }}">出库</a>
                            {% endif %}
                            <a href="{% url 'BPlan:inventory_show_detail_html' %}?id={{ inventory.inventory_id }}">详细信息</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    {% endif %}
{#    <p>{{ request.path }}</p>#}
    {#    <div class="pure-g">#}
    {#        {% for inventory in paginator %}#}
    {#            <div class="pure-u-1 pure-u-md-1-3">#}
    {#                <div class="show-body-card">#}
    {#                    <div class="show-body-card-header">#}
    {#                        <div class="inventory-name"><label>名称</label> {{ inventory.inventory_name }}</div>#}
    {#                        <div class="inventory-id">#}
    {#                             <i class="iconfont icon-user-id"></i> {{ inventory.inventory_id }}&nbsp;&nbsp; <label>创建者</label> {{ inventory.inventory_create_user_name }}&nbsp;&nbsp;<label>创建日期</label> {{ inventory.inventory_create_time.month }}月{{ inventory.inventory_create_time.day }}日#}
    {#                        </div>#}
    {#                    </div>#}
    {#                    <div class="show-body-card-body">#}
    {#                        库存分组：{{ inventory.inventory_group }}<br>#}
    {#                        库存数量：{{ inventory.inventory_num }}<br>#}
    {#                        单价：{{ inventory.inventory_price }}<br>#}
    {#                        备注：{{ inventory.inventory_mark }}<br>#}
    {#                    </div>#}
    {#                    <div class="show-body-card-footer">#}
    {#                        <a class="show-body-card-footer-a"#}
    {#                           href="{% url 'BPlan:inventory_change_html' %}?type=0&id={{ inventory.inventory_id }}">入库</a>#}
    {#                        <a class="show-body-card-footer-a"#}
    {#                           href="{% url 'BPlan:inventory_change_html' %}?type=1&id={{ inventory.inventory_id }}">出库</a>#}
    {#                        <a class="show-body-card-footer-a"#}
    {#                           href="{% url 'BPlan:inventory_show_detail_html' %}?id={{ inventory.inventory_id }}">详细信息</a>#}
    {#                    </div>#}
    {#                </div>#}
    {#            </div>#}
    {#        {% endfor %}#}
    {#    </div>#}
{% endblock %}
{% block script %}
    <script>
        $(document).ready(function () {
            let flag = true;
            let height;
            if (window.screen.width > 768) {
                height = (parseInt(($('.group-choice').length - 1) / 3) + 1) * 74;
            } else {
                height = $('.group-choice').length * 74;
            }

            $('.groups-switch').click(
                function () {
                    if (flag) {
                        $('#groups').css('height', height + 'px');
                        $('.groups-switch-1').addClass('groups-switch-change-1');
                        $('.groups-switch-2').addClass('groups-switch-change-2');
                    } else {
                        $('#groups').css('height', '0');
                        $('.groups-switch-1').removeClass('groups-switch-change-1');
                        $('.groups-switch-2').removeClass('groups-switch-change-2');
                    }
                    flag = !flag;
                }
            );
            $('#excel').click(function () {
                window.location.href = '{% url "BPlan:excel_inventory" %}'
            });
        })
    </script>
{% endblock %}