BPlan/urls.py
from django.urls import path
from . import view_common, view_user, views_inventory, view_customer, view_excel

app_name = "BPlan"


urlpatterns = [
    path('test/', view_excel.test, name="test"),

    # path('index/whetherLogin/', view_common.whether_login, name='whether_login'),
    path('index/', view_common.index, name='index'),
    # path('markdown/', view_common.markdown_html, name='markdown'),

    path('login/', view_user.login_html, name='login'),
    # path('login/loginCheck/', view_user.login_check, name='login_check'),
    path('login/logout/', view_user.login_logout, name='login_logout'),
    path('login/record/', view_user.login_record_html, name='login_record_html'),
    # path('login/record/ask/', view_user.login_record_ask_html, name='login_record_ask_html'),
    # path('register/', view_user.register_html, name='register_html'),
    # path('register/check/', view_user.register_check, name='register_check'),
    # path('change/password/', view_user.change_password_html, name='change_password_html'),
    # path('change/password/check/', view_user.change_password_check, name='change_password_check'),
    # path('change/question/', view_user.change_question_html, name='change_question_html'),
    # path('change/question/check/', view_user.change_question_check, name='change_question_check'),
    # path('change/personalInformation/', view_user.change_personal_information, name='change_personal_information'),

    path('inventory/show/all/', views_inventory.inventory_show_all_html, name='inventory_show_all_html'),
    path('inventory/show/detail/', views_inventory.inventory_show_detail_html, name='inventory_show_detail_html'),
    path('inventory/create/', views_inventory.inventory_create, name='inventory_create_html'),
    # path('inventory/create/add/', views_inventory.inventory_create_add, name='inventory_create_add'),
    path('inventory/change/', views_inventory.inventory_change, name='inventory_change_html'),
    # path('inventory/change/add/', views_inventory.inventory_change_add, name='inventory_change_add'),
    path('inventory/change/detail/', views_inventory.inventory_change_detail, name='inventory_change_detail'),
    path('inventory/search/', views_inventory.inventory_search, name='inventory_search'),
    path('inventory/operation/', views_inventory.inventory_operation_html, name='inventory_operation_html'),
    path('inventory/operation/chart/', views_inventory.inventory_operation_chart_html, name='inventory_operation_chart_html'),
    path('inventory/group/create/', views_inventory.inventory_group_create, name='inventory_group_create_html'),
    # path('inventory/group/create/add/', views_inventory.inventory_group_create_add, name='inventory_group_create_add'),

    path('customer/show/all/', view_customer.customer_show_all_html, name='customer_show_all_html'),
    path('customer/show/detail/', view_customer.customer_show_detail_html, name='customer_show_detail_html'),
    path('customer/search/', view_customer.customer_search, name='customer_search'),
    path('customer/create/', view_customer.customer_create_html, name='customer_create_html'),
    # path('customer/create/add/', view_customer.customer_create_add, name='customer_create_add'),
    path('customer/tracking/', view_customer.customer_tracking, name='customer_tracking'),
    path('customer/change/detail/', view_customer.customer_change_detail, name='customer_change_detail'),
    path('customer/excel/', view_customer.customer_excel, name='customer_excel'),

    path('excel/inventory/', view_excel.inventory_excel, name='excel_inventory'),
    path('excel/inventory_operation/', view_excel.inventory_operation_excel, name='excel_inventory_operation'),
    path('excel/customer/', view_excel.customer_excel, name='excel_customer'),  # 导出全部客户信息
    path('excel/login_record', view_excel.login_record_excel, name='excel_login_record'),

    # path('verificationCode/get/', VerificationCode.verification_code, name='getVerificationCode'),

    # WXApi URL:
    # path('wx/login/', WXApi.wx_login_check, name='wx_login_check'),
    # path('wx/logout/', WXApi.wx_logout, name='wx_logout'),
]

ResearchAndTrainingBPlan/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('BPlan/', include('BPlan.urls', namespace="BPlan")),
    path('', RedirectView.as_view(url='BPlan/index/')),  # 如果不输入详细网址，直接重定向到主页
]

templates/PC/customer/customerChangeDetail.html
{% extends 'PC/base/baseForm.html' %}
{% block title %}
更改客户信息
{% endblock %}
{% block body-title %}
更改客户信息
{% endblock %}
{% block style %}
<style>
    .pure-form-aligned .pure-control-group label{
        width: 7em;
    }
@media screen and (min-width: 768px) {
    textarea{
        height: 17em;
    }
}
</style>
{% endblock %}
{% block form %}
<div class="pure-g">
<div class="pure-u-1 pure-u-xl-1-2">
    <input type="text" id="id" name="id" value="{{ customer.id }}" hidden>
    <div class="pure-control-group">
        <label for="name">客户名称</label>
        <input type="text" id="name" name="name" value="{{ customer.name }}" required maxlength="50"/>
    </div>
    <div class="pure-control-group">
        <label for="project_name">项目名称</label>
        <input type="text" id="project_name" name="project_name" value="{{ customer.project_name }}" maxlength="50" required/>
    </div>
    <div class="pure-control-group">
        <label for="user_id">业务填写人</label>
        <select id="user_id" name="user_id" required>
            {% for user in user_list %}
                <option value="{{ user.user_id }}" {% if customer.user_id == user %} selected {% endif %}>{{ user.user_name }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="pure-control-group">
        <label for="contact">联系人</label>
        <input type="text" id="contact" name="contact" value="{{ customer.contact }}" maxlength="20" required/>
{#        <select id="contact" name="contact" required>#}
{#            {% for user in user_list %}#}
{#                <option value="{{ user.user_id }}" {% if customer.user_id == user %} selected {% endif %}>{{ user.user_name }}</option>#}
{#            {% endfor %}#}
{#        </select>#}
    </div>
    <div class="pure-control-group">
        <label for="tel">联系方式</label>
        <input type="text" id="tel" name="tel" value="{{ customer.tel }}" maxlength="20" required/>
    </div>
    <div class="pure-control-group">
        <label for="project_amount">项目金额</label>
        <input type="text" id="project_amount" name="project_amount" value="{{ customer.project_amount }}" maxlength="20" required/>
    </div>
    <div class="pure-control-group">
        <label for="payment_method">付款方式</label>
        <input type="text" id="payment_method" name="payment_method" value="{{ customer.payment_method }}" maxlength="20" required/>
    </div>
</div>
<div class="pure-u-1 pure-u-xl-1-2">
    <div class="pure-control-group">
        <label for="mark">项目技术要求或主要条款</label>
        <textarea id="mark" name="mark" maxlength="1000" required>{{customer.mark}}</textarea>
    </div>
</div>
</div>
{% endblock %}
{% block button-text %}
<i class="iconfont icon-wancheng"></i> 提交
{% endblock %}
{#{% block script %}#}
{#<script>#}
{#$(document).ready(function () {#}
{#    let error = $('.error');#}
{#    let login_button = $('.form-button');#}
{#    login_button.click(function () {#}
{#        login_button.html('<i class="iconfont icon-jiazai"></i> 请稍后...').attr('disabled', 'disabled');  // 改变button中的文字#}
{#        if (NoEmpty('<i class="iconfont icon-wancheng"></i> 提交', error, login_button)) {#}
{#            $.ajax({#}
{#                url: "{% url 'BPlan:customer_change_detail' %}",#}
{#                type: 'POST',#}
{#                data: {#}
{#                    'id': {{ customer.id }},#}
{#                    'name': $('#name').val(),#}
{#                    'contact': $('#contact').val(),#}
{#                    'tel': $('#tel').val(),#}
{#                    'project_name': $('#project_name').val(),#}
{#                    'project_amount': $('#project_amount').val(),#}
{#                    'payment_method': $('#payment_method').val(),#}
{#                    'mark': $('#mark').val(),#}
{#                    "csrfmiddlewaretoken":$("[name='csrfmiddlewaretoken']").val(),#}
{#                },#}
{#                success: function () {#}
{#                    error.text("");#}
{#                    $("form").hide(1000);#}
{#                    $(".body-title").html("修改成功！");#}
{#                    return 1;#}
{#                },#}
{#            })#}
{#        }#}
{##}
{#    })#}
{#})#}
{#</script>#}
{#{% endblock %}#}

templates/PC/customer/customerCreate.html
{% extends 'PC/base/baseForm.html' %}
{% load staticfiles %}
{% block title %}创建客户信息{% endblock %}
{% block body-title %}创建客户信息{% endblock %}
{% block style %}
    <style>
        .pure-form-aligned .pure-control-group label {
            width: 7em;
        }

        @media screen and (min-width: 768px) {
            textarea {
                height: 20em;
            }
        }
    </style>
{% endblock %}
{% block form %}
    <div class="pure-g">
        <div class="pure-u-1 pure-u-xl-1-2">
            <div class="pure-control-group">
                <label for="name">客户名称</label>
                <input type="text" id="name" name="name" value="" placeholder="请输入客户名称" required maxlength="50"/>
            </div>
            <div class="pure-control-group">
                <label for="project_name">项目名称</label>
                <input type="text" id="project_name" name="project_name" value="" placeholder="请输入项目名称" required
                       maxlength="50"/>
            </div>
            <div class="pure-control-group">
                <label for="project_date">项目签订时间</label>
                <input type="date" id="project_date" name="project_date" value="" required/>
            </div>
            <div class="pure-control-group">
                <label for="user_id">项目签订时间</label>
                <select id="user_id" name="user_id" required>
                    {% for user in user_list %}
                        <option value="{{ user.user_id }}">{{ user.user_name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="pure-control-group">
                <label for="contact">联系人</label>
                <input type="text" id="contact" name="contact" value="" placeholder="请输入联系人" required maxlength="20"/>
            </div>
            <div class="pure-control-group">
                <label for="tel">联系方式</label>
                <input type="text" id="tel" name="tel" value="" placeholder="请输入联系方式" required maxlength="20"/>
            </div>
            <div class="pure-control-group">
                <label for="project_amount">项目金额</label>
                <input type="text" id="project_amount" name="project_amount" value="" placeholder="项目金额" maxlength="20"
                       required/>
            </div>
            <div class="pure-control-group">
                <label for="payment_method">付款方式</label>
                <input type="text" id="payment_method" name="payment_method" value="" placeholder="付款方式" maxlength="20"
                       required/>
            </div>
        </div>
        <div class="pure-u-1 pure-u-xl-1-2">
            <div class="pure-control-group">
                <label for="mark">项目技术要求或主要条款</label>
                <textarea id="mark" name="mark" placeholder="请输入项目技术要求或主要条款（1000字以内）" maxlength="1000"
                          required></textarea>
            </div>
        </div>
    </div>
    {#<div class="pure-control-group">#}
    {#    <label for="code">验证码</label>#}
    {#    <input type="text" name="code" id="code" value="" placeholder="验证码" maxlength="4" minlength="4" required style="width: calc(17em - 100px - 5px)"/>#}
    {#    <img class="code" onclick="refreshSrc()"/>#}
    {#</div>#}
{% endblock %}
{% block button-text %}
    <i class="iconfont icon-wancheng"></i> 创建
{% endblock %}
{#{% block script %}#}
{#<script>#}
{#$(document).ready(function () {#}
{#    let error = $('.error');#}
{#    let login_button = $('.form-button');#}
{#    login_button.click(function () {#}
{#        login_button.html('<i class="iconfont icon-jiazai"></i> 请稍后...').attr('disabled', 'disabled');  // 改变button中的文字#}
{#        if (NoEmpty('<i class="iconfont icon-wancheng"></i> 创建', error, login_button)){#}
{#            $.ajax({#}
{#                url: "{% url 'BPlan:customer_create_add' %}",#}
{#                type: 'POST',#}
{#                data: {#}
{#                    'name': $('#name').val(),#}
{#                    'contact':$('#contact').val(),#}
{#                    'tel':$('#tel').val(),#}
{#                    'project_name':$('#project_name').val(),#}
{#                    'project_date':$('#project_date').val(),#}
{#                    'project_amount':$('#project_amount').val(),#}
{#                    'payment_method':$('#payment_method').val(),#}
{#                    'mark':$('#mark').val(),#}
{#                    "csrfmiddlewaretoken":$("[name='csrfmiddlewaretoken']").val(),#}
{#                },#}
{#                success: function (result) {#}
{#                    if (result === 'success') {#}
{#                        error.text("");#}
{#                        $("form").hide(1000);#}
{#                        $(".body-title").html("<i class=\"iconfont icon-wancheng\"></i> 创建成功");#}
{#                        return 1;#}
{#                    }#}
{#                },#}
{#            })#}
{#        }#}
{##}
{#    })#}
{#})#}
{#</script>#}
{#{% endblock %}#}

templates/PC/customer/customerSearch.html
{% extends 'PC/base/baseShow.html' %}
{% block title %}
    查找客户信息
{% endblock %}
{% block style %}
    <style>
        .body-title {
            font-size: 1em;
            text-align: center;
            width: 85%;
            margin: 70px auto;
            color: black;
            border-bottom: white solid 2px;
        }

        .pure-form select {
            padding: 0 .6em;
            height: 38.8px;
        }

        .show-footer {
            display: none;
        }

        .search-button {
            color: white;
        {#display: block;#} height: 2.3em;
            width: 6em;
            margin: 0;
            padding: 0;
            background-color: var(--bkcolor);
            border: solid white 2px;
            border-radius: 3px;
            transition: background-color 0.5s;
            -webkit-transition: background-color 0.5s;
        }

        .search-button:hover {
            color: var(--bkcolor);
            background-color: white;
        }

        .show-body-card-footer-a {
            width: 48.5%;
        }

        @media only screen and (max-width: 768px) {
            .body-title {
                font-size: 1em;
                padding: 20px 0;
                letter-spacing: normal;
                margin: 20px auto;
                width: 100%;
            }

            .search-button {
                display: none;
            }
        }
    </style>
{% endblock %}
{% block body-title %}
    <form class="pure-form" method="get" action="{% url 'BPlan:customer_search' %}">
        <select id="search_type" name="search_type" style="display: inline-block">
            <option value="all">综合查询</option>
            <option value="name">客户名称</option>
            <option value="project_name">项目名称</option>
            <option value="user">业务填写人</option>
            <option value="contact">联系人</option>
            <option value="tel">联系方式</option>
            <option value="project_amount">项目金额</option>
            <option value="payment_method">付款方式</option>
            <option value="mark">主要条款</option>
        </select>
        <input type="search" name="search" id="search" placeholder="请输入关键词查询" required maxlength="20"
               style="display: inline-block; margin: 0" value="{{ search }}">
        <button type="submit" class="search-button">查询客户</button>
    </form>
{% endblock %}
{% block show-body %}
    {% if search_type == '' %}
    {% elif paginator.count == 0 %}
        <p class="not-found">>>抱歉，未找到相关库存信息<<</p>
    {% else %}
        <div class="table-box">
            <table class="show-table">
                <thead>
                <tr>
                    <th>客户名称</th>
                    <th>项目名称</th>
                    <th>项目签订时间</th>
                    <th>业务填写人</th>
                    <th>联系人</th>
                    <th>联系方式</th>
                    <th>项目金额</th>
                    <th>付款方式</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for customer in page.object_list %}
                    <tr>
                        <td>{{ customer.name }}</td>
                        <td>{{ customer.project_name }}</td>
                        <td>{{ customer.project_date }}</td>
                        <td>{{ customer.user_id }}</td>
                        <td>{{ customer.contact }}</td>
                        <td>{{ customer.tel }}</td>
                        <td>{{ customer.project_amount }}</td>
                        <td>{{ customer.payment_method }}</td>
                        <td>
                            {% if request.session.user_identity %}
                            <a href="{% url 'BPlan:customer_tracking' %}?id={{ customer.id }}">添加跟踪记录</a>
                            {% endif %}
                            <a href="{% url 'BPlan:customer_show_detail_html' %}?id={{ customer.id }}">详细信息</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    {% endif %}
{% endblock %}
{% block script %}
    <script>
        $(document).ready(function () {
            $('option').each(function () {
                if ($(this).val() === '{{ search_type }}') {
                    $(this).attr('selected', 'selected');
                } else {
                    $(this).removeAttr('selected');
                }
            })
            $('#excel').click(function () {
                window.location.href = '{% url "BPlan:excel_customer" %}';
            });
        })
    </script>
{% endblock %}

templates/PC/customer/customerShowAll.html
{% extends 'PC/base/baseShow.html' %}
{% load staticfiles %}
{% block title %}
全部客户信息
{% endblock %}
{% block body-title %}
全部客户信息
{% endblock %}
{% block show-body %}
    {% if page.object_list.count != 0 %}
        <div class="table-box">
            <table class="show-table">
                <thead>
                <tr>
                    <th>客户名称</th>
                    <th>项目名称</th>
                    <th>项目签订时间</th>
                    <th>业务填写人</th>
                    <th>联系人</th>
                    <th>联系方式</th>
                    <th>项目金额</th>
                    <th>付款方式</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for customer in page.object_list %}
                    <tr>
                        <td>{{ customer.name }}</td>
                        <td>{{ customer.project_name }}</td>
                        <td>{{ customer.project_date }}</td>
                        <td>{{ customer.user_id }}</td>
                        <td>{{ customer.contact }}</td>
                        <td>{{ customer.tel }}</td>
                        <td>{{ customer.project_amount }}</td>
                        <td>{{ customer.payment_method }}</td>
                        <td>
                            {% if request.session.user_identity %}
                            <a href="{% url 'BPlan:customer_tracking' %}?id={{ customer.id }}">添加跟踪记录</a>
                            {% endif %}
                            <a href="{% url 'BPlan:customer_show_detail_html' %}?id={{ customer.id }}">详细信息</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    {% endif %}
{#    <div class="pure-g">#}
{#    {% for customer in paginator %}#}
{#        <div class="pure-u-1 pure-u-md-1-3">#}
{#            <div class="show-body-card">#}
{#                <div class="show-body-card-header">#}
{#                    <div class="inventory-name"><label>客户名称</label> {{ customer.name }}</div>#}
{#                    <div class="inventory-id">{# <i class="iconfont icon-user-id"></i> {{ inventory.inventory_id }}&nbsp;&nbsp; <label>工程名称</label> {{ customer.project_name }}{# <label>项目签订时间</label> {{ customer.project_date.month }}月{{ customer.project_date.day }}日 </div>#}
{#                </div>#}
{#                <div class="show-body-card-body">#}
{#                    联系人：{{ customer.contact }}<br>#}
{#                    联系方式：{{ customer.tel }}<br>#}
{#                    项目金额：{{ customer.project_amount }}<br>#}
{#                    付款方式：{{ customer.payment_method }}<br>#}
{#                    项目签订时间：{{ customer.project_date }}<br>#}
{#                </div>#}
{#                <div class="show-body-card-footer">#}
{#                    <a class="show-body-card-footer-a" href="{% url 'BPlan:inventory_change_html' %}?type=0&id={{ inventory.inventory_id }}">入库</a>#}
{#                    <a class="show-body-card-footer-a" href="{% url 'BPlan:customer_tracking' %}?id={{ customer.id }}">添加跟踪记录</a>#}
{#                    <a class="show-body-card-footer-a" href="{% url 'BPlan:customer_show_detail_html' %}?id={{ customer.id }}">详细信息</a>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    {% endfor %}#}
{#    </div>#}
{% endblock %}
{% block script %}
    <script>
        $(document).ready(function () {
            $('#excel').click(function () {
                window.location.href = '{% url "BPlan:excel_customer" %}'
            });
        })
    </script>
{% endblock %}
{#{% block script %}#}
{#<script>#}
{#$(document).ready(function () {#}
{#    let flag = true;#}
{#    let height;#}
{#    if (window.screen.width>768){#}
{#        height = (parseInt(($('.group-choice').length-1) / 3) + 1) * 74;#}
{#    }#}
{#    else {#}
{#        height = $('.group-choice').length * 74;#}
{#    }#}
{##}
{#    $('.groups-switch').click(#}
{#        function () {#}
{#            if (flag) {#}
{#                $('#groups').css('height', height+'px');#}
{#                $('.groups-switch-1').addClass('groups-switch-change-1');#}
{#                $('.groups-switch-2').addClass('groups-switch-change-2');#}
{#            }#}
{#            else {#}
{#                $('#groups').css('height', '0');#}
{#                $('.groups-switch-1').removeClass('groups-switch-change-1');#}
{#                $('.groups-switch-2').removeClass('groups-switch-change-2');#}
{#            }#}
{#            flag = !flag;#}
{#        }#}
{#    );#}
{#})#}
{#</script>#}
{#{% endblock %}#}

templates/PC/customer/customerShowDetail.html
{% extends 'PC/base/baseDetail.html' %}
{% load staticfiles %}
{% block title %}
客户详细信息
{% endblock %}
{% block body-title %}
客户详细信息
{% endblock %}
{% block style %}
<style>
.detail-footer{
    width: 90%;
    min-width: unset;
    margin: 0 auto;
}
@media screen and (max-width: 768px) {
    .detail-footer button{
        margin: 8px auto;
    }
}
</style>
{% endblock %}
{% block detail-contain %}
{#    <h1>客户名称</h1>#}
{#    <li>{{ customer.name }}</li>#}
{#    <h1>联系人</h1>#}
{#    <li>{{ customer.contact }}</li>#}
{#    <h1>联系方式</h1>#}
{#    <li>{{ customer.tel }}</li>#}
{#    <h1>项目名称</h1>#}
{#    <li>{{ customer.project_name }}</li>#}
{#    <h1>项目签订时间</h1>#}
{#    <li>{{ customer.project_date }}</li>#}
{#    <h1>项目金额</h1>#}
{#    <li>{{ customer.project_amount}}</li>#}
{#    <h1>付款方式</h1>#}
{#    <li>{{ customer.payment_method }}</li>#}
{#    <h1>项目技术要求或主要条款</h1>#}
{#    <li>{{ customer.mark }}</li>#}
{#    <h1>业务填写人</h1>#}
{#    <li>{{ user }}</li>#}
{#    <h1>项目跟踪记录</h1>#}
{#    {% for track in tracking %}#}
{#        <li>{{ track.track_date }} | {{ track.track_state }}</li>#}
{#    {% endfor %}#}
    <table>
        <tr><td>客户名称</td><td colspan="2">{{ customer.name }}</td></tr>
        <tr><td>项目名称</td><td colspan="2">{{ customer.project_name }}</td></tr>
        <tr><td>项目签订时间</td><td colspan="2">{{ customer.project_date }}</td></tr>
        <tr><td>业务填写人</td><td colspan="2">{{ customer.user_id }}</td></tr>
        <tr><td>联系人</td><td colspan="2">{{ customer.contact }}</td></tr>
        <tr><td>联系方式</td><td colspan="2">{{ customer.tel }}</td></tr>
        <tr><td>项目金额</td><td colspan="2">{{ customer.project_amount }}</td></tr>
        <tr><td>付款方式</td><td colspan="2">{{ customer.payment_method }}</td></tr>
        <tr><td>项目技术要求<br>或主要条款</td><td colspan="2">{{ customer.mark }}</td></tr>
        {% for tracking_item in tracking %}
            {% if forloop.counter == 1 %}
                <tr><td rowspan="{{ tracking.count }}">项目跟踪记录</td><td>{{ tracking_item.track_date }}</td><td>{{ tracking_item.track_state }}</td></tr>
            {% else %}
                <tr><td class="special-td">{{ tracking_item.track_date }}</td><td class="special-td">{{ tracking_item.track_state }}</td></tr>
            {% endif %}
        {% endfor %}
{#        <tr><td>项目跟踪记录</td><td>{{ inventory.inventory_recent_change_time }}</td></tr>#}
    </table>
{% endblock %}
{% block detail-footer %}
{#    <div class="pure-u-1 pure-u-md-1-2">#}
{#        <div><button id="changeIn"><i class="iconfont icon-ruku"></i> 入库</button></div>#}
{#    </div>#}
{#    <div class="pure-u-1 pure-u-md-1-2">#}
{#        <div><button id="changeOut"><i class="iconfont icon-chuku"></i> 出库</button></div>#}
{#    </div>#}
    {% if request.session.user_identity %}
        <div class="pure-u-1 pure-u-md-1-2">
            <div>
                <button id="change"><i class="iconfont icon-change"></i> 修改客户信息</button>
            </div>
        </div>
        <div class="pure-u-1 pure-u-md-1-2">
            <div>
                <button id="customerTracking"><i class="iconfont icon-churukujilu"></i> 添加项目跟踪记录</button>
            </div>
        </div>
    {% endif %}
    <div class="pure-u-1 pure-u-md-1-2">
        <div><button id="excel"><i class="iconfont icon-Excel"></i> 导出Excel</button></div>
    </div>
{% endblock %}
{% block script %}
<script>
$(document).ready(function () {
    {% if request.session.user_identity %}
    $('#change').click(function () {
        window.location.href = '{% url "BPlan:customer_change_detail" %}?id={{ customer.id }}'
    });
    $('#customerTracking').click(function () {
        window.location.href = '{% url "BPlan:customer_tracking" %}?id={{ customer.id }}'
    });
    {% endif %}
    $('#excel').click(function () {
        window.location.href = '{% url "BPlan:customer_excel" %}?id={{ customer.id }}'
    })
})
</script>
{% endblock %}

templates/PC/customer/customerTracking.html
{% extends 'PC/base/baseForm.html' %}
{% load staticfiles %}
{% block title %}添加项目跟踪记录{% endblock %}
{% block style %}
<style type="text/css">
.pure-form-aligned .pure-control-group label{
    width: 7em;
}
</style>
{% endblock %}
{% block body-title %}添加项目跟踪记录{% endblock %}
{% block form %}
    <input type="text" id="id" name="id" required readonly value="{{ id }}" hidden/>
    <div class="pure-control-group">
        <label for="customer">客户</label>
        <input type="text" name="customer" id="customer" value="{{ name }}" readonly/>
    </div>
    <div class="pure-control-group">
        <label for="track_date">跟踪时间记录</label>
        <input type="date" name="track_date" id="track_date" required/>
    </div>
    <div class="pure-control-group">
        <label for="track_state">项目跟踪状态</label>
        <input type="text" name="track_state" id="track_state" placeholder="请输入项目跟踪状态" maxlength="50" required/>
    </div>
{% endblock %}
{% block button-text %}
<i class="iconfont icon-wancheng"></i> 创建
{% endblock %}
{#{% block script %}#}
{#    <script type="text/javascript">#}
{#    $(document).ready(function () {#}
{#        let error = $('.error');#}
{#        let login_button = $('.form-button');#}
{#        login_button.click(function () {#}
{#            login_button.html('<i class="iconfont icon-jiazai"></i> 请稍后...').attr('disabled', 'disabled');  // 改变button中的文字#}
{#            if(NoEmpty('<i class="iconfont icon-wancheng"></i> 创建', error, login_button)){#}
{#                $.ajax({#}
{#                    url: '{% url 'BPlan:customer_tracking' %}',#}
{#                    data: {#}
{#                        'id': {{ id }},#}
{#                        'track_date': $('#track_date').val(),#}
{#                        'track_state': $('#track_state').val(),#}
{#                        "csrfmiddlewaretoken":$("[name='csrfmiddlewaretoken']").val(),#}
{#                    },#}
{#                    type: 'POST',#}
{#                    success: function (result) {#}
{#                        if (result === 'success') {#}
{#                            $("form").hide(1000);#}
{#                            $(".body-title").text("创建成功");#}
{#                            return 1;#}
{#                        }#}
{#                    },#}
{#                })#}
{#            }#}
{#        })#}
{#    })#}
{#    </script>#}
{#{% endblock %}#}