BPlan/urls.py
from django.urls import path
from . import view_common, view_user, views_inventory, view_customer, view_excel

app_name = "BPlan"


urlpatterns = [
    path('test/', view_excel.test, name="test"),

    # path('index/whetherLogin/', view_common.whether_login, name='whether_login'),
    path('index/', view_common.index, name='index'),
    # path('markdown/', view_common.markdown_html, name='markdown'),

    path('login/', view_user.login_html, name='login'),
    # path('login/loginCheck/', view_user.login_check, name='login_check'),
    path('login/logout/', view_user.login_logout, name='login_logout'),
    path('login/record/', view_user.login_record_html, name='login_record_html'),
    # path('login/record/ask/', view_user.login_record_ask_html, name='login_record_ask_html'),
    # path('register/', view_user.register_html, name='register_html'),
    # path('register/check/', view_user.register_check, name='register_check'),
    # path('change/password/', view_user.change_password_html, name='change_password_html'),
    # path('change/password/check/', view_user.change_password_check, name='change_password_check'),
    # path('change/question/', view_user.change_question_html, name='change_question_html'),
    # path('change/question/check/', view_user.change_question_check, name='change_question_check'),
    # path('change/personalInformation/', view_user.change_personal_information, name='change_personal_information'),

    path('inventory/show/all/', views_inventory.inventory_show_all_html, name='inventory_show_all_html'),
    path('inventory/show/detail/', views_inventory.inventory_show_detail_html, name='inventory_show_detail_html'),
    path('inventory/create/', views_inventory.inventory_create, name='inventory_create_html'),
    # path('inventory/create/add/', views_inventory.inventory_create_add, name='inventory_create_add'),
    path('inventory/change/', views_inventory.inventory_change, name='inventory_change_html'),
    # path('inventory/change/add/', views_inventory.inventory_change_add, name='inventory_change_add'),
    path('inventory/change/detail/', views_inventory.inventory_change_detail, name='inventory_change_detail'),
    path('inventory/search/', views_inventory.inventory_search, name='inventory_search'),
    path('inventory/operation/', views_inventory.inventory_operation_html, name='inventory_operation_html'),
    path('inventory/operation/chart/', views_inventory.inventory_operation_chart_html, name='inventory_operation_chart_html'),
    path('inventory/group/create/', views_inventory.inventory_group_create, name='inventory_group_create_html'),
    # path('inventory/group/create/add/', views_inventory.inventory_group_create_add, name='inventory_group_create_add'),

    path('customer/show/all/', view_customer.customer_show_all_html, name='customer_show_all_html'),
    path('customer/show/detail/', view_customer.customer_show_detail_html, name='customer_show_detail_html'),
    path('customer/search/', view_customer.customer_search, name='customer_search'),
    path('customer/create/', view_customer.customer_create_html, name='customer_create_html'),
    # path('customer/create/add/', view_customer.customer_create_add, name='customer_create_add'),
    path('customer/tracking/', view_customer.customer_tracking, name='customer_tracking'),
    path('customer/change/detail/', view_customer.customer_change_detail, name='customer_change_detail'),
    path('customer/excel/', view_customer.customer_excel, name='customer_excel'),

    path('excel/inventory/', view_excel.inventory_excel, name='excel_inventory'),
    path('excel/inventory_operation/', view_excel.inventory_operation_excel, name='excel_inventory_operation'),
    path('excel/customer/', view_excel.customer_excel, name='excel_customer'),  # 导出全部客户信息
    path('excel/login_record', view_excel.login_record_excel, name='excel_login_record'),

    # path('verificationCode/get/', VerificationCode.verification_code, name='getVerificationCode'),

    # WXApi URL:
    # path('wx/login/', WXApi.wx_login_check, name='wx_login_check'),
    # path('wx/logout/', WXApi.wx_logout, name='wx_logout'),
]

ResearchAndTrainingBPlan/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('BPlan/', include('BPlan.urls', namespace="BPlan")),
    path('', RedirectView.as_view(url='BPlan/index/')),  # 如果不输入详细网址，直接重定向到主页
]

templates/PC/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" crossorigin="anonymous">
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/grids-responsive-min.css">
    <link rel="stylesheet" href="//at.alicdn.com/t/font_1281820_jae5r1wdpjn.css">
    <link rel="stylesheet" href="{% static 'PC/css/base.css' %}">
    {% block link %}

    {% endblock %}
</head>
<body>
<div class="body-left">
    <div class="header">
        <div class="header-logo">
            <label>库存管理系统</label>
        </div>
        {#        <div class="header-button">#}
        {#            <hr class="header-line">#}
        {#            <a class="header-menu-a header-button-a" href="{% url 'BPlan:login' %}"><i class="iconfont icon-login"></i> 登录</a>#}
        {#            <a class="header-menu-a header-button-a" href="{% url 'BPlan:register_html' %}"><i class="iconfont icon-register"></i> 注册</a>#}
        {#        </div>#}
        <div class="header-user">
            <hr class="header-line">
            <i class="header-user-name iconfont icon-yuangong" style="font-size: 1.3em">{{ request.session.user_name }}</i>
            <a class="header-menu-a header-button-a header-button-a-logout" href="{% url 'BPlan:login_logout' %}"><i
                    class="iconfont icon-logout"></i> 退出登录</a>
        </div>
        <ul class="header-menu-ul">
            <li class="header-menu-li">
                <hr class="header-line">
                <a href="{% url 'BPlan:index' %}" id="header-menu-1" class="header-menu-a"><i
                        class="iconfont icon-shouye"></i> 主页</a>
            </li>
            <li class="header-menu-li">
                <hr class="header-line">
                <i class="iconfont icon-kucun"></i> 库存
                <ul class="header-menu-ul">
                    <li class="header-menu-li">
                        <a href="{% url 'BPlan:inventory_show_all_html' %}" class="header-menu-a">
                            <i class="iconfont icon-cangchu"></i> 全部库存
                        </a>
                    </li>
                    {#                    <li class="header-menu-li"><a#}
                    {#                            href="{% url 'BPlan:inventory_search' %}?search_type=inventory_create_user_name&search=我"#}
                    {#                            class="header-menu-a"><i class="iconfont icon-yuangong"></i> 我创建的</a></li>#}
                    <li class="header-menu-li">
                        <a href="{% url 'BPlan:inventory_search' %}" class="header-menu-a">
                            <i class="iconfont icon-kucunchaxun"></i> 查找库存
                        </a>
                    </li>
                    {#                    <li class="header-menu-li"><a href="{% url 'BPlan:inventory_operation_html' %}" class="header-menu-a"><i class="iconfont icon-churukujilu"></i> 查询库存操作记录</a></li>#}
{#                    <li class="header-menu-li">#}
{#                        <a href="{% url 'BPlan:inventory_group_create_html' %}" class="header-menu-a">#}
{#                            <i class="iconfont icon-NewGroup"></i> 创建新的库存分组#}
{#                        </a>#}
{#                    </li>#}
{#                    <li class="header-menu-li">#}
{#                        <a href="{% url 'BPlan:inventory_create_html' %}" class="header-menu-a">#}
{#                            <i class="iconfont icon-create"></i> 创建新的库存#}
{#                        </a>#}
{#                    </li>#}
                    <li class="header-menu-li">
                        <a href="{% url 'BPlan:inventory_operation_html' %}?type=user" class="header-menu-a">
                            <i class="iconfont icon-churukujilu"></i> 我的操作记录
                        </a>
                    </li>
                    {% if request.session.user_identity == 1 %}
                    <li class="header-menu-li">
                        <a href="{% url 'BPlan:inventory_group_create_html' %}" class="header-menu-a">
                            <i class="iconfont icon-NewGroup"></i> 创建新的库存分组
                        </a>
                    </li>
                    <li class="header-menu-li">
                        <a href="{% url 'BPlan:inventory_create_html' %}" class="header-menu-a">
                            <i class="iconfont icon-create"></i> 创建新的库存
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </li>
            <li class="header-menu-li header-menu-has-children">
                <hr class="header-line">
                <i class="iconfont icon-customer"></i> 客户
                <ul class="header-menu-ul">
                    <li class="header-menu-li"><a href="{% url 'BPlan:customer_show_all_html' %}" class="header-menu-a"><i
                            class="iconfont icon-form"></i> 全部客户信息</a></li>
{#                    <li class="header-menu-li"><a href="{% url 'BPlan:customer_search' %}?search_type=user&search=我"#}
{#                                                  class="header-menu-a"><i class="iconfont icon-yuangong"></i> 我创建的</a>#}
{#                    </li>#}
                    <li class="header-menu-li"><a href="{% url 'BPlan:customer_search' %}" class="header-menu-a"><i
                            class="iconfont icon-customer-search"></i> 查询客户信息</a></li>
                    {% if request.session.user_identity == 1 %}
                    <li class="header-menu-li"><a href="{% url 'BPlan:customer_create_html' %}" class="header-menu-a"><i
                            class="iconfont icon-NewCustomer"></i> 创建客户信息</a></li>
                    {% endif %}
                </ul>
            </li>
{#            <li class="header-menu-li header-menu-has-children">#}
{#                <hr class="header-line">#}
{#                <i class="iconfont icon-tongji"></i> 数据#}
{#                <ul class="header-menu-ul">#}
{#                    <li class="header-menu-li"><a href="{% url 'BPlan:inventory_operation_chart_html' %}"#}
{#                                                  class="header-menu-a"><i class="iconfont icon-Statistics"></i>#}
{#                        每日出入库</a></li>#}
                    {#                    <li class="header-menu-li"><a href="#" class="header-menu-a">库存统计</a></li>#}
                    {#                    <li class="header-menu-li"><a href="{% url 'BPlan:login_record_ask_html' %}" class="header-menu-a"><i class="iconfont icon-ask-record"></i> 网站访问量统计</a></li>#}
{#                </ul>#}
{#            </li>#}
            <li class="header-menu-li header-menu-has-children">
                <hr class="header-line">
                <i class="iconfont icon-yuangong"></i> 我的
                <ul class="header-menu-ul">
                    {#                    <li class="header-menu-li"><a href="{% url 'BPlan:change_password_html' %}" class="header-menu-a"#}
                    {#                                                  id="change-password"><i class="iconfont icon-xiugaimima"></i> 修改密码</a>#}
                    {#                    </li>#}
                    {#                    <li class="header-menu-li"><a href="{% url 'BPlan:change_question_html' %}" class="header-menu-a"><i#}
                    {#                            class="iconfont icon-anquan"></i> 更改密保问题</a></li>#}
                    {#                    <li class="header-menu-li"><a href="{% url 'BPlan:change_personal_information' %}?page=show"#}
                    {#                                                  class="header-menu-a"><i#}
                    {#                            class="iconfont icon-personal-information"></i> 个人信息</a></li>#}
                    {#                    <li class="header-menu-li"><a href="{% url 'BPlan:change_personal_information' %}?page=change" class="header-menu-a"><i class="iconfont icon-change"></i> 修改个人信息</a></li>#}
                    {#                    <li class="header-menu-li"><a href="{% url 'BPlan:inventory_operation_html' %}?type=user" class="header-menu-a"><i class="iconfont icon-churukujilu"></i> 我的操作记录</a></li>#}
                    <li class="header-menu-li"><a href="{% url 'BPlan:login_record_html' %}?page=1"
                                                  class="header-menu-a"><i class="iconfont icon-cloud-history"></i>
                        我的访问记录</a></li>
                </ul>
            </li>
            <li class="header-menu-li header-menu-has-children">
                <hr class="header-line">
                <i class="iconfont icon-site"></i> 站点
                <ul class="header-menu-ul">
                    {% if request.session.user_identity == 1 %}
                    <li class="header-menu-li"><a href="/admin/" class="header-menu-a" id="change-password"
                                                  target="_blank"><i class="iconfont icon-admin"></i> 进入后台</a></li>
                    {% endif %}
                    {#                    <li class="header-menu-li"><a href="{% url 'BPlan:markdown' %}?file=操作手册" class="header-menu-a"><i class="iconfont icon-readme"></i> 操作手册</a></li>#}
                    {#                    <li class="header-menu-li"><a href="{% url 'BPlan:markdown' %}?file=更新日志" class="header-menu-a"><i class="iconfont icon-refreshBook"></i> 更新日志</a></li>#}
                    <li class="header-menu-li"><a href="https://github.com/1184291824/ResearchAndTrainingBPlan"
                                                  class="header-menu-a" target="_blank"><i
                            class="iconfont icon-git"></i> Github</a></li>
                </ul>
            </li>
        </ul>
    </div>
    <div class="header-picker">
        <i class="iconfont icon-header-picker"></i>
    </div>
</div>
<div class="body-right">
    {% block body %}

    {% endblock %}
</div>

{#    <footer class="footer">#}
{#        <p>声明：本网站仅作为南京理工大学电光学院科研训练项目《多用户登录的库存管理系统》展示使用</p>#}
{#        <p>本网站版权归MYZ所有</p>#}
{#    </footer>#}
</body>
{#<script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>#}
<script src="{% static 'PC/js/jquery-3.4.1.min.js' %}"></script>
<script type="text/javascript">
    //function refreshSrc(){  //刷新验证码图片
    {#$('.code').attr('src', "{% url 'BPlan:getVerificationCode' %}?" + new Date().getTime());#}
    //}
    function NoEmpty(ButtonHtml, error, button) {  // 检查输入框是否为空
        let check = true;
        $('input').each(function () {
            if (!this.value || this.value.trim() == "") {
                let label = this.previousElementSibling;
                error.text(label.innerText + "不允许为空");
                button.html(ButtonHtml).removeAttr('disabled');
                check = false;
                return 0;
            }
        });
        return check;
    }

    {#// 读取cookie#}
    {#function getCookie(c_name) {#}
    {#    if (document.cookie.length > 0) {#}
    {#        let c_start = document.cookie.indexOf(c_name + "=")#}
    {#        if (c_start != -1) {#}
    {#            c_start = c_start + c_name.length + 1#}
    {#            let c_end = document.cookie.indexOf(";", c_start)#}
    {#            if (c_end == -1)#}
    {#                c_end = document.cookie.length#}
    {#            return unescape(document.cookie.substring(c_start, c_end))#}
    {#        }#}
    {#    }#}
    {#    return ""#}
    {#}#}

    {#$(document).ready(function () {#}
        {#$.ajax({#}
        {#    url: '{% url 'BPlan:whether_login' %}',#}
        {#    success: function(result){#}
        {#        if (result['login_status'] === 0) {#}
        {#            $('.header-button').css('display', 'block');#}
        {#        } else{#}
        {#            $('.header-user').css('display', 'block');#}
        {#            $('.header-user-name').text(result['user_name']);#}
        {#        }#}
        {#    }#}
        {# }) #}
    {#    let user = getCookie('user_name');#}
    {#    $('.header-user-name').text(decodeURI(user.replace(/\\\\x/g, '%').slice(3, -2).toUpperCase()));#}
    {#});#}
</script>
{% block script %}

{% endblock %}

</html>

templates/PC/base/baseChart.html
{% extends 'PC/base/base.html' %}
{% block link %}
<style>
canvas{
    margin: 2em auto;
}
.chart{
    width: 80%;
    height: auto;
    margin: 20px auto;
    text-align: center;
    background-color: white;
    padding: 20px 0;
}
@media screen and (max-width: 768px){
    .chart{
        width: 90%;
        padding: 0;
    }
    canvas{
        margin-top: 0;
    }
}
</style>
{% block style %}{% endblock %}
{% endblock %}
{% block body %}
    <div class="body-title">{% block body-title %}{% endblock %}</div>
    <div class="chart">
    {% block chart-canvas %}

    {% endblock %}
    </div>

{% endblock %}
{% block script %}
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0/dist/Chart.bundle.min.js" integrity="sha256-xKeoJ50pzbUGkpQxDYHD7o7hxe0LaOGeguUidbq6vis=" crossorigin="anonymous"></script>
<script>
var options = {
    layout: {
        padding: {
            left: 10,
            right: 10,
            top: 10,
            bottom: 10,
        }
    },
    legend: { // 图例
        labels: {
            fontColor: 'gray',
            fontSize: 16,
        }
    },
    scales: { // 坐标线
        yAxes: [{
            ticks: {
                beginAtZero: true,
                suggestedMax: 10,
            }
        }]
    },
    title: { // 图表标题
        display: true,
        text: '',
        fontSize: 18, // 字号18px
    }
};
var normal_datasets = {
    backgroundColor: 'rgba(54, 162, 235, 0.2)',
    borderColor: '#36a2eb',
    pointBorderColor: 'rgba(54, 162, 235, 0.2)',
    pointBorderWidth: '5',
    pointRadius: '4',
    pointBackgroundColor: '#36a2eb',
    pointHoverRadius: '6',
    pointHoverBorderColor: 'rgba(54, 162, 235, 0.2)',
    pointHoverBorderWidth: '7',
};
</script>
{% block script-more %}

{% endblock %}
{% endblock %}

templates/PC/base/baseDetail.html
{% extends 'PC/base/base.html' %}
{% load staticfiles %}
{% block link %}
    <link href="{% static 'PC/css/detail.css' %}" rel="stylesheet">
    {% block style %}

    {% endblock %}
{% endblock %}
{% block body %}
<div class="body-title"><label>{% block body-title %}{% endblock %}</label></div>
    <div class="detail">
        <div class="detail-contain">{% block detail-contain %}{% endblock %}</div>
        <div class="detail-footer">
            <div class="pure-g">{% block detail-footer %}{% endblock %}</div>
        </div>
    </div>
{% endblock %}

templates/PC/base/baseForm.html
{% extends 'PC/base/base.html' %}
{% load staticfiles %}
{% block link %}
    <link rel="stylesheet" href="{% static 'PC/css/form.css' %}">
    <script type="application/javascript">
        window.onload = function () {
            let login_button = $('.form-button');
            {#login_button.click(function () {#}
            {#    login_button.html(#}
            {#        '<i class="iconfont icon-jiazai"></i> 请稍后...'#}
            {#    );#}
            {#    // 这里有一个待解决的问题，如何禁用button#}
            {# }) // 改变button中的文字#}
            let form = $('.form form');  // 获取表单
            form.submit(function () {
                login_button.html(
                    '<i class="iconfont icon-jiazai"></i> 请稍后...'
                ).attr('disabled', 'disabled');
            })
        }
    </script>
    {% block style %}{% endblock %}
{% endblock %}
{% block body %}
    <div class="body-title"><label>{% block body-title %}{% endblock %}</label></div>
    <div class="form">
        <form class="pure-form pure-form-aligned" method="post" action="#">
            <fieldset>
                {% csrf_token %}
                {% block form %}

                {% endblock %}
                <div class="error">{{ error }}</div>
                <button class="form-button" type="submit">{% block button-text %}{% endblock %}</button>
            </fieldset>
        </form>
    </div>
{% endblock %}

templates/PC/base/baseShow.html
{% extends 'PC/base/base.html' %}
{% load staticfiles %}
{% block link %}
    <link rel="stylesheet" href="{% static 'PC/css/show.css' %}">
    <style>
    </style>
    {% block style %}{% endblock %}
{% endblock %}
{% block body %}
    <div class="body-title">{% block body-title %}{% endblock %}</div>
    {% block group-choice %}{% endblock %}
    <div class="show-body">
        {% block show-body %}{% endblock %}
        {% if paginator.num_pages > 1 %}
            <div class="show-paginator">
                <ul class="pagination">
                    {% if page.has_previous %}
                        <li><a href="?{% for k,v in request.GET.items %}{% if k != "page" %}{{ k }}={{ v }}&{% endif %}{% endfor %}page=1">«</a></li>
                        <li><a href="?{% for k,v in request.GET.items %}{% if k != "page" %}{{ k }}={{ v }}&{% endif %}{% endfor %}page={{ page.previous_page_number }}">‹</a></li>
                    {% endif %}
                    {% for foo in paginator.page_range %}
                        <li><a href="?{% for k,v in request.GET.items %}{% if k != "page" %}{{ k }}={{ v }}&{% endif %}{% endfor %}page={{ foo }}">{{ foo }}</a></li>
                    {% endfor %}
                    {% if page.has_next %}
                        <li><a href="?{% for k,v in request.GET.items %}{% if k != "page" %}{{ k }}={{ v }}&{% endif %}{% endfor %}page={{ page.next_page_number }}">›</a></li>
                        <li><a href="?{% for k,v in request.GET.items %}{% if k != "page" %}{{ k }}={{ v }}&{% endif %}{% endfor %}page={{ paginator.num_pages }}">»</a></li>
                    {% endif %}
                </ul>
            </div>
        {% endif %}
        {% if paginator.count > 0 %}
            <div class="detail-footer">
                <div class="pure-g">
                    <div class="pure-u-1 pure-u-md-1-3">
                        <div>
                            <button id="excel"><i class="iconfont icon-Excel"></i> 导出Excel</button>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}